### ISSUE TITLE
very slow to invalidate for small chagnes

### ISSUE THREAD

**Issue by joaquingrech** [chrfalch/NControl#35]
Hi

The invalidate method is bad for graphics. It should probably allow for partial invalidation or a way not to force a full redrawn.
Let me explain the situation.
Try to create a progressbar that increases from 0 to the full width of the screen. One pixel at a time.
1) Override Draw, but it gets an empty canvas so you have to draw the full rectangle every time.
2) Wait for an Invalidate call to redraw everything again.

This is extremely slow. You will see flickering on the control. The options are to either allow for some kind of double buffer so it doesn't flicker or speed it up considerably by allowing partial redraws.

Here just as an example, my code to test it. Just call Progress on a loop from 0 to 1 incrementing by 0.001 for instance (1000 pixels width).

public class MyProgressBar : NControlView
    {
        public static readonly BindableProperty BarColorProperty =
            BindableProperty.Create<MyProgressBar, Xamarin.Forms.Color>
        (p => p.BarColor, Xamarin.Forms.Color.Blue);

```
    public Xamarin.Forms.Color BarColor
    {
        get { return (Xamarin.Forms.Color)GetValue(BarColorProperty); }
        set { SetValue(BarColorProperty, value); }
    }

    public static readonly BindableProperty ProgressProperty =
        BindableProperty.Create<MyProgressBar, double>
    (p => p.Progress, 0);

    public double Progress
    {
        get { return (double)GetValue(ProgressProperty); }
        set {
                SetValue (ProgressProperty, value);
                this.Invalidate ();
        //  }
        }
    }

    public MyProgressBar()
    {
    }

    public override void Draw(NGraphics.ICanvas canvas, NGraphics.Rect rect)
    {
        //if (prevRect == 0) {
            canvas.FillRectangle (rect.X, rect.Y, rect.Width * Progress, rect.Height, Colors.Orange);
    /*      prevRect = rect.Width * Progress;
        } else { // draw only the new lines
            double newWidth=(rect.Width * Progress)-prevRect;
            if (newWidth > 0) {
                canvas.FillRectangle (prevRect, rect.Y, newWidth, rect.Height, Colors.Orange);
                prevRect = prevRect + newWidth;
            }
        }*/
    }
}
```

**Comment by chrfalch** [comment]
Hi @joaquingrech. 

NControl was never intended to be a library for doing fast 2D-graphics. It is a library created to help you create custom controls using as much shared code as possible, so the limitations you describe are known and also part of the design. 

The way we suggest you create a control like this is to build it as a composited control. This is often how UX controls are created, since it meets your requirements about minimal redrawing.

**Here is a description of how we'd create such a control with NControl:**
- Create an outer control where you draw the outline of the progress control - this will only be redrawn when the control is created/sized.
- Create the filler control (f.ex a blue bar) that you redraw everytime you want to respond to the current value of the progress bar.

We also recommend that you use translations in Xamarin.Forms when moving, scaling and rotating controls - it is mapped by the library to the best native implementations on every given platform. This could be used to avoid redrawing the bar in your control when the value updates.

If you want more control over your drawing we suggest you use custom renderers. 

As a last note, the project NControl.Controls (which is publicly available on NuGet but not officially released) contains few example controls that are all created with NControl to show the possibilities - and for some of them we've had to use custom renderers to accomplish what we need.

Chris
