### ISSUE TITLE
Update NGraphics to 0.4.0

### ISSUE THREAD

**Issue by chrfalch** [chrfalch/NControl#46]

**Comment by patridge** [comment]
If there is anything another person could do to help with this, I'd certainly love to try. I'm working on a custom NControl that works with SVGs. It "works fine" (doesn't crash), but displays all the SVG rendering issues fixed since 0.3.1.

**Comment by chrfalch** [comment]
Hi,

Try downloading the latest source and upgrade. The thing you'd need to do
is to update the NGraphics package and try to compile. There might be a few
errors, specifically with missing implementations in our Windows code. Try
fixing these and see if it works.

Chris

**Comment by patridge** [comment]
I actually did the package update before I commented, and all compiled successfully.*
*I didn't have the Windows projects loaded because I'm running entirely in Xamarin Studio on a Mac.

Let me see if I can make room on a Windows VM for all the various Windows and Windows Phone SDK and emulators and such. It could take a while since it wants an additional 23GB just for those things. I'm hoping I can install the SDKs alone (+16GB) just to test compilation, but that could still be overly optimistic.

**Comment by patridge** [comment]
I put my Windows VM in a basically unusable state (outside VS) to get everything installed and I still can't get even the current develop branch to build on Windows. It complains about `InitializeComponent` not existing for the XAML file in the Forms demo project.

I'll have to defer to someone who can actually test the various Windows platforms. Sorry I couldn't be more help after all. I really did want to get this change in place.

**Comment by patridge** [comment]
FWIW, I could certainly start a PR with the core/iOS/Android changes that get made, but with as small as the changes are to update NGraphics, it probably isn't worth it. https://github.com/chrfalch/NControl/compare/develop...patridge:update-ngraphics-0.4.0

**Comment by chrfalch** [comment]
Thanks for helping out- the problem is the windows part of the control, it contains a simple renderer that needs updating.
Chris
