### ISSUE TITLE
NControl.UWP ?

### ISSUE THREAD

**Issue by JimSEOW** [chrfalch/NControl#57]
Please create NControl.UWP

Is NControl.Win compatible with UWP? How to port 
`Touch.FrameReported +=  Touch_FrameReported;` to UWP?

```
public abstract class NControlViewRendererBase : ViewRenderer<NControlView, Border>
{
    protected static void Initialize()
    {
        Touch.FrameReported += Touch_FrameReported; 
    }
}
```

**Comment by chrfalch** [comment]
Not yet; but we're considering it. Download the code and do your best to understand it; I do not have any direct answers to how to port at the moment - if I had; it would be because it was already ported ;-)

**Comment by BlueRaja** [comment]
http://stackoverflow.com/questions/36670422/how-do-i-make-an-existing-c-sharp-library-uwp-compatible

I still don't feel I fully understand it _(hence the 200 rep bounty)_, so if anyone figures it out, please let me know, because I have several projects which could also benefit from supporting UWP.

Apparently even if a library wouldn't even use _any_ UWP features, it still needs to explicitly add support for it or users of UWP can't use the library.

**Comment by JimSEOW** [comment]
NControl has many lines of codes useful for learning custom rendering (e.g Win Phone 8.1). Good Job!
The alternative will be SkiaSharp for UWP, twitted works Feb 2016
