### ISSUE TITLE
Multi-touch (android?)

### ISSUE THREAD

**Issue by eric4wan** [chrfalch/NControl#63]
Hey there - 

First off, great library - it's making my life a million times easier.

I've implemented NControl into a Xamarin shared project to create a sort-of cropping tool. I've overridden the Touch events and they're all behaving as expected with the exception that the IEnumerable<Point> parameters only contain ONE point. My code shoouuld be set up to iterate through and handle multi-touch, but I'm only seeing the first touch coming through.

(This has only been tested on the Android side - haven't gotten around to swinging the iOS side yet)

Thoughts?

**Comment by slam023** [comment]
You may have it working by now. What I've did on Android part for multitouch support to work on my drawing application. Instead of passing a position data to Element.TouchesMoved(touchInfo); I passed an object which have the information on it's pointer id and the position of the pointer. For iOS, I will do the same even though there is no pointer id but we can generate one for it.

**Comment by chrfalch** [comment]
Pull request #72 is now merged.
